version: '2'

services:

  redinkblogapi:
    image: redink-blog-api
    environment:
      - DB_HOST=redinkblogdb
      - DB_PORT=3306
      - DB_USER=redinkblog
      - DB_PASS=redinkblog@12345
      - DB_DBASE=redinkblog
      - MAIL_HOST=redinkmailhog
      - MAIL_PORT=1025
      - MAIL_SENDER_ADDRESS=dummyblogalerts@redinkmailhog
      - MAIL_SENDER_NAME="Dummy Blog Alerts"
      - MAIL_USER=dummyblogalerts@redinkmailhog
      - MAIL_PASS=abc@123_mail
      - MAIL_SECURE=0
      - MAIL_START_TLS=0
      - MAIL_STRICT_TLS=0
      - JWT_ACCESS_TOKEN_SECRET=rANd0m34673
      - JWT_REFRESH_TOKEN_SECRET=RanD0M65749
    build:
      context: .
      dockerfile: redink-blog-api.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - "redinkblogdb"
      - "redinkmailhog"
    restart: "on-failure"
    volumes:
      - redinkblogapi-data:/home/node/app

  redinkblogdb:
    image: mysql:8.0.27
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --init-file /docker-entrypoint-initdb.d/dummy.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root@12345
      - MYSQL_DATABASE=redinkblog
      - MYSQL_USER=redinkblog
      - MYSQL_PASSWORD=redinkblog@12345
    ports:
      - "3306:3306"
    restart: "on-failure"
    volumes:
      - redinkblogdb-data:/var/lib/mysql
      - ./schemas/dummy.sql:/docker-entrypoint-initdb.d/dummy.sql

  redinkmailhog:
    image: mailhog/mailhog:v1.0.1
    environment:
      - MH_HOSTNAME=redinkmailhog
      - MH_STORAGE=maildir
    restart: "on-failure"
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - redinkmailhog-data:/maildir

volumes:
  redinkblogapi-data:
  redinkblogdb-data:
  redinkmailhog-data: